CREATE TABLE user (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password TEXT NOT NULL,
  salt TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE image (
  id SERIAL PRIMARY KEY,
  image_id UUID,
  path VARCHAR(255) NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE share_link (
  id SERIAL PRIMARY KEY,
  link VARCHAR(255) NOT NULL,
  image_id INT NOT NULL,
  usage_count INT NOT NULL DEFAULT 0,
  max_usage_count INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (image_id) REFERENCES image(id)
);